---
actions:
  to: skaffold.yaml
---
apiVersion: skaffold/v2beta6
kind: Config
profiles:
  - name: local
    build:
      artifacts:
        - image: dev.local/{{artifactId}}
          buildpacks:
            builder: paketobuildpacks/builder:tiny
            env: 
              - BP_BOOT_NATIVE_IMAGE=1
              - BP_BOOT_NATIVE_IMAGE_BUILD_ARGUMENTS=-Dspring.native.remove-yaml-support=true
          dependencies:
            paths:
              - src
              - pom.xml
      tagPolicy:
        sha256: {}
      local:
        push: false
    deploy:
      kustomize:
        paths:
          - kubernetes/service.yaml
